### ISSUE TITLE
Add a flag to remove process_* and go_* 

### ISSUE THREAD

**Issue by svenXY** [raffis/mongodb-query-exporter#154]
Hi,

we use this nice service to feed metrics into Datadog. Unfortunately, it is not easy to tell datadog to ignore certain metrics and custom metrics cost money.

The metrics starting with go_ and process_ are not necessary for me, so I'd prefer to remove them if possible.

#### Describe the solution you'd like
A config item and/or environment variable that would filter out those metrics

#### Describe alternatives you've considered
Try to filter at the receiving side (i.e. datadog agent), but it is not possible

**Comment by raffis** [comment]
I don't think so its appropriate to support this as these metrics are very much common. Unwanted metrics should rather be ditched at scrape time. With prometheus you can ignore metrics by a prefix using a relabel_rule. I am not used to datadog but have you checked if they offer that option?
