### ISSUE TITLE
customizable http endpoint path to metrics

### ISSUE THREAD

**Issue by theliuk** [raffis/mongodb-query-exporter#19]
#### Is your feature request related to a problem? Please describe
Our platform requires (as a convention) all the services to expose metrics at`GET /-/metrics` http endpoint.
mongodb-query-exporter exposes the metrics at `GET /metrics`. It'd be useful to allow the user to choose the path at which the metrics are exposed.

#### Describe the solution you'd like
A simple configuration parameter, like `metricsEndpointPath`

**Comment by raffis** [comment]
@theliuk This is now available in v1.0.0-beta7 (See readme, or cmd help).
