### ISSUE TITLE
Stale data and "retry" on query error?

### ISSUE THREAD

**Issue by n0guest** [raffis/mongodb-query-exporter#2]
Hello, Raffael.

Recently I found this in logs:

```
Mar 16 02:20:03 mongoz-72927 mongodb_query_exporter[22759]: time="2020-03-16T02:20:03+03:00" level=error msg="failed to handle metric metric requests_status aggregation returned an emtpy result set, abort listen on metric requests_status"
Mar 16 02:20:03 mongoz-72927 mongodb_query_exporter[22759]: time="2020-03-16T02:20:03+03:00" level=error msg="failed to handle metric metric requests_status aggregation returned an emtpy result set, abort listen on metric requests_status"
```

And after that exporter doesn't export an "actual" value for metric, but keeps a stale one. But the stale data could be misleading in many ways. I suggest don't export "stale" value for metric at all. Also, probably a better way to handle this —  to add a `retry` option? When target collection will be available for queries again, the exporter will continue its work.

What do you think about that?

PS: MongoDB 3.0, i.e. in "pull mode" (w/out "change streams").

**Comment by raffis** [comment]
> And after that exporter doesn't export an "actual" value for metric, but keeps a stale one. But the stale data could be misleading in many ways. I suggest don't export "stale" value for metric at all. Also, probably a better way to handle this — to add a `retry` option? When target collection will be available for queries again, the exporter will continue its work.
> 
> What do you think about that?

Yeah absolutely required. I reckon there should be a retry interval which gets increased after each (failed) retry. Also I need to check what possible errors actually could happen.
This will be most likely be an out of the box solution/fix, there should be no need to manually configure a retry possibility.

**Comment by raffis** [comment]
I've pushed some fixes to master including a fix for your request. Actually this might be as easy as just not "abort" and let the interval take on as you suggested. I did a few tests and it looks like it could work. Note I did not create the next beta yet.

**Comment by n0guest** [comment]
> I've pushed some fixes to master including a fix for your request. Actually this might be as easy as just not "abort" and let the interval take on as you suggested. I did a few tests and it looks like it could work.

Looks like it really works like it supposed to:

> Mar 20 02:20:01 mongoz-72927 mongodb_query_exporter[22063]: time="2020-03-20T02:20:01+03:00" level=error msg="failed to handle metric metric requests_status aggregation returned an emtpy result set, awaiting the next pull. failed with error requests_status"
> Mar 20 02:20:01 mongoz-72927 mongodb_query_exporter[22063]: time="2020-03-20T02:20:01+03:00" level=info msg="wait 5s to refresh metric requests_status"
> Mar 20 02:20:01 mongoz-72927 mongodb_query_exporter[22063]: time="2020-03-20T02:20:01+03:00" level=error msg="failed to handle metric metric requests_status aggregation returned an emtpy result set, awaiting the next pull. failed with error requests_status"
> Mar 20 02:20:01 mongoz-72927 mongodb_query_exporter[22063]: time="2020-03-20T02:20:01+03:00" level=info msg="wait 5s to refresh metric requests_status"
> Mar 20 02:20:01 mongoz-72927 mongodb_query_exporter[22063]: time="2020-03-20T02:20:01+03:00" level=error msg="failed to handle metric metric test1 aggregation returned an emtpy result set, awaiting the next pull. failed with error test1"
> Mar 20 02:20:01 mongoz-72927 mongodb_query_exporter[22063]: time="2020-03-20T02:20:01+03:00" level=info msg="wait 5s to refresh metric test1"

BTW, these logs are from "collection-was-recreated" scenario. I didn't have an opportunity to test it on "empty-for-now" collection. But I guess, expected behavior should be the same.

> Note I did not create the next beta yet.

Not a problem at all. I've built binary myself using commands from `travis.yml`.
