### ISSUE TITLE
can not isntall helmchart anymore

### ISSUE THREAD

**Issue by Loki-Afro** [raffis/mongodb-query-exporter#236]
#### Describe the bug
our github action which installs your chart in a kubernetes cluster is failing with the following error message

```
{"changed": false, "command": "/usr/local/bin/helm --version=3.0.1 show chart oci://ghcr.io/raffis", "msg": "Failure when executing Helm command. Exited 1.\nstdout: \nstderr: Error: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Araffis%3Apull&scope=repository%3Auser%2Fimage%3Apull&service=ghcr.io: 403 Forbidden\n", "stderr": "Error: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Araffis%3Apull&scope=repository%3Auser%2Fimage%3Apull&service=ghcr.io: 403 Forbidden\n", "stderr_lines": ["Error: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Araffis%3Apull&scope=repository%3Auser%2Fimage%3Apull&service=ghcr.io: 403 Forbidden"], "stdout": "", "stdout_lines": []}
```

when using helm (and i'm not an expert!) locally to issue the same command it fails too
```
zarathustra@esel ~ % helm --version=3.0.1 show chart oci://ghcr.io/raffis
Error: failed to authorize: failed to fetch anonymous token: unexpected status: 400 Bad Request
```

#### Expected behavior

listing and installing of the helm chart works again

#### Environment
 - mongodb-query-exporter version: 3.0.1
 - prometheus version: dunno
 - MongoDB version: 4.4
 - Deployed as: kubernetes

**Comment by raffis** [comment]
Hey 👋🏻 , the oci url you're using is wrong. You are supposed to use `oci://ghcr.io/raffis/charts/mongodb-query-exporter`.
Also you should go with the latest v5.1.0 if possible.

**Comment by Loki-Afro** [comment]
yes wrong url indeed.

but nevermind, the bug was/is somewhere else https://github.com/actions/runner-images/issues/8475

newest helm version has an issue where it can't pull charts from with oci-urls anymore as far as i understood
