### ISSUE TITLE
Erro deploy default image

### ISSUE THREAD

**Issue by fernandoscruz** [raffis/mongodb-query-exporter#25]
Hi can you help me? I can't run the image on kubernetes on kubernetes.

It may not have / bin / bash

Error response from daemon: OCI runtime create failed: container_linux.go: 348: starting container process caused "exec: \" / bin / sh \ ": stat / bin / sh: no such file or directory": unknown [kubelet, dev -0-6020372984483016836]

**Comment by raffis** [comment]
You can't start a shell in this image, it is based on a distroless image and only contains the binary.
What exactly are you trying to achieve?

(On kubernetes you may use the helm chart to deploy the exporter: https://github.com/raffis/mongodb-query-exporter/tree/master/chart/prometheus-mongodb-query-exporter)
