### ISSUE TITLE
Query problem with a "like" match value

### ISSUE THREAD

**Issue by cerealekiller-mike** [raffis/mongodb-query-exporter#268]
#### Describe the bug
I'm trying to build an exporter to retrieve all documents where the Id match for 2 conditions

#### To Reproduce
My pipeline is

[
      {
         "$sort":{
            "createDate":-1
         }
      },
      {
        "$match":{
          "_id": {"$in":["/123./", "/134./"]}
        }
      },
      {
        "$project": {
          "_id": 0, 
          "createDate": {
                          "$dateToString": {
                            "format": "%d/%m/%Y %H:%M:%S",
                            "date": "$createDate"
                          }
                         }
        }
      },
      {
         "$limit": 1
      }
    ]       

#### Expected behavior
In my case when I put a direct _id like '1234567' the aggeration works but if I put a like /123./ the query returns nothing. It's looks like the "match" condition is not correctly written.

#### Environment
 - mongodb-query-exporter version: latest
 - prometheus version: N/A
 - MongoDB version: v4.0.0
 - Deployed as: docker

#### Additional context

There a specific syntax for this case ? 

Thanks

**Comment by cerealekiller-mike** [comment]
I've opened as a bug but in fact is a question. Sorry

**Comment by raffis** [comment]
Are you attempting to do a regex match? This won't work like this. The regex in quotes here is just a simple string. 
You need to use $regex (but that won't work with $in) => https://www.mongodb.com/docs/manual/reference/operator/query/regex/#-regex-vs.--pattern--syntax
