### ISSUE TITLE
MongoDB Compatibility Matrix

### ISSUE THREAD

**Issue by fredmaggiowski** [raffis/mongodb-query-exporter#269]
#### Is your feature request related to a problem? Please describe

Hi there, is there a way to know the currently supported MongoDB version and whether the tool is compatible with the recent MongoDB 7 release?

I've seen action are running against MongoDB 5 and I figure that as long as the exporter is running aggregates possibile compatibility issues that may rise are solely related to the aggregates themeselves, is there something the exporter does that may cause incompatibilities? 

At the end of the day it would be nice to know the currently supported versions, does it make sense to you? :)

#### Describe the solution you'd like

Github action running against multiple version/README doc?

**Comment by raffis** [comment]
I am not aware of incompatibilities as long as you use supported features of the aggregation.
But yes the the tests should definitely invoke v7 as well 👍🏻
