### ISSUE TITLE
How to use "new Date(0)" in pipeline

### ISSUE THREAD

**Issue by ambarit** [raffis/mongodb-query-exporter#27]
I have the following pipeline:

pipeline: |
    [
    {"$match": {"book": {"$ne": null}}},{"$group": {"_id": "$env", "timestamp": {"$last": "$timestamp"}, "bookability": {"$last": 
    {"$multiply": ["$book",100]}}}}, {"$project": {"_id": "$_id", "bookability": "$bookability", **"timestamp": {"$substr": [{"$subtract": 
    ["$timestamp", new Date(0)]}, 0, -1]}}}**
    ]

The idea behind this is to receive a metric (bookability) with two labels:
- _id - the name of the environment;
- timestamp - in epoch time, in string format. Therefore I can decode it in Prometheus.

The problem I have is with the timestamp parameter in the project part of the expression.
The above expression in the exact same format provides adequate result in mongo:
{ "_id" : "my_environment", "timestamp" : "1624349380000", "bookability" : 97.38846572361263 }

However, if I try to start the mongodb_exporter using the above pipeline I receive the below error:

```
{"level":"info","ts":1624371064.4728699,"caller":"v2/config.go:71","msg":"will listen on 0.0.0.0:9412"}
{"level":"info","ts":1624371064.4731367,"caller":"v2/config.go:101","msg":"use mongodb hosts []string{\"localhost:27017\"}"}
panic: failed to decode json aggregation pipeline: error decoding key 2.$project.timestamp.$substr.0.$subtract: invalid JSON literal. Position: 276, literal: new 

goroutine 1 [running]:
github.com/raffis/mongodb-query-exporter/cmd.glob..func1(0x14b67e0, 0x14f3f98, 0x0, 0x0)
        /home/thristov/mongodb-query-exporter-prometheus-mongodb-query-exporter-1.1.3/cmd/root.go:64 +0x3f6
github.com/spf13/cobra.(*Command).execute(0x14b67e0, 0xc00018a010, 0x0, 0x0, 0x14b67e0, 0xc00018a010)
        /home/thristov/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x14b67e0, 0x0, 0xcf6ee0, 0xc000114058)
        /home/thristov/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/thristov/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/raffis/mongodb-query-exporter/cmd.Execute(...)
        /home/thristov/mongodb-query-exporter-prometheus-mongodb-query-exporter-1.1.3/cmd/root.go:97
main.main()
        /home/thristov/mongodb-query-exporter-prometheus-mongodb-query-exporter-1.1.3/main.go:8 +0x2e
```

If I enclose new Date(0) in quotes like "$new Date(0)" I am able to start the exporter but the result is empty both from the exporter and from mongo. 

So my questions is, **how can I add new Date(0) to the pipeline so that the exporter accepts it correctly?**

**Comment by raffis** [comment]
You can't use js functions here,  the pipeline needs to be pure json. Also see https://github.com/raffis/mongodb-query-exporter/issues/12#issuecomment-725721956. You might be able to use $$NOW if mongod is at least 4.2 or use "$date" for static datetime strings.

**Comment by ambarit** [comment]
Thank you very much @raffis! This solved my issue. 

I created a new date parameter in the group part of the query - epoch, containing the epoch time. For this I used $date. Then I subtracted the epoch time from my date timestamp and received the timestamp in epoch time. You can close this issue.

`  pipeline: |
   [
   {"$match": {"book": {"$ne": null}}},{"$group": {"_id": "$env", "timestamp": {"$last": "$timestamp"}, "bookability": {"$last": 
   {"$multiply": ["$book",100]}}, **"epoch": {"$last": {"$date": "1970-01-01T00:00:00Z"}}**}}, {"$project": {"_id": "$_id", "bookability": 
   "$bookability", **"timestamp": {"$substr": [{"$subtract": ["$timestamp", "$epoch"]}, 0, -1]}**}}
   ]
`
