### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by theliuk** [raffis/mongodb-query-exporter#28]
Hi, we just wanted to know if this project is still active. At the moment, we are using the beta release and we were wondering if any stable release is expected in the near future.

Thank you

**Comment by raffis** [comment]
> Hi, we just wanted to know if this project is still active. At the moment, we are using the beta release and we were wondering if any stable release is expected in the near future.
> 
> Thank you

Hi @theliuk, yes this project is active, it should be considered stable even though there is no official stable version out yet, will release soonish.
