### ISSUE TITLE
Can't take ObjectId("xyz") in the pipeline

### ISSUE THREAD

**Issue by jinsiang2008** [raffis/mongodb-query-exporter#3]
Looks like it can't take ObjectId("xyz") in the pipeline. Could we support that?
`pipeline: |
    [
      {"$match":{"user_id":ObjectId("xyz")}},
      {"$group":{"_id":null,"count":{"$sum":1}}},
      {"$project":{"_id":0, "count":1}}
    ]`

Will return error:
`failed to handle metric failed to decode json aggregation pipeline: invalid JSON input.`

**Comment by raffis** [comment]
> Looks like it can't take ObjectId("xyz") in the pipeline. Could we support that?
> `pipeline: | [ {"$match":{"user_id":ObjectId("xyz")}}, {"$group":{"_id":null,"count":{"$sum":1}}}, {"$project":{"_id":0, "count":1}} ]`

You have to use the json notion of ObjectId("xyz") which is:
```
{"$oid": "xyz"}
```

**Comment by jinsiang2008** [comment]
> > Looks like it can't take ObjectId("xyz") in the pipeline. Could we support that?
> > `pipeline: | [ {"$match":{"user_id":ObjectId("xyz")}}, {"$group":{"_id":null,"count":{"$sum":1}}}, {"$project":{"_id":0, "count":1}} ]`
> 
> You have to use the json notion of ObjectId("xyz") which is:
> 
> ```
> {"$oid": "xyz"}
> ```

Ah, thanks @raffis , the json notion really helps.
I will close this ticket.
