### ISSUE TITLE
Mongodb aggregate date

### ISSUE THREAD

**Issue by lulanascimento** [raffis/mongodb-query-exporter#31]
Hi, First thank you very much for the tool.
Is it possible to make queries by date range?

**Comment by raffis** [comment]
> Hi, First thank you very much for the tool. Is it possible to make queries by date range?

You can run anything which is supported by MongoDB aggregations. For date ranges I guess you want to include something up to current timestamp, there have been a couple of questions related to this, see https://github.com/raffis/mongodb-query-exporter/issues/27#issuecomment-866126304
