### ISSUE TITLE
Ability to extract replica set related info

### ISSUE THREAD

**Issue by artazar** [raffis/mongodb-query-exporter#35]
Hi,

Tried the exporter and it works nice for custom queries to collections.

I also have a specific need to query replica set statu ( rs.status() ) and put certain details into grafana dashboard. A nice improvement would be to allow that.

Thanks,

**Comment by raffis** [comment]
Hi

This exporter is only intended to to create custom query metrics. If you need metrics for mongodb internals you can use https://github.com/percona/mongodb_exporter. You can also easily run both exporters.
