### ISSUE TITLE
Programmatically add metrics

### ISSUE THREAD

**Issue by spacekbnueve** [raffis/mongodb-query-exporter#36]
Is there a way to programmatically add metrics ?

For example, I'd like to monitor the total number of documents in all collections.
When a new collection is created, do I have to edit the exporter config file and restart or there's another way ?

Thanks for you help.

**Comment by raffis** [comment]
Thats not supported since aggregations are by collection and there is no way to fetch collections within an aggregation (as far as I am aware). 
However if you only want the total number of documents overall you can check other mongodb exporters which might export that number.

**Comment by spacekbnueve** [comment]
Got it thanks !
