### ISSUE TITLE
The query problem

### ISSUE THREAD

**Issue by gongmingsong** [raffis/mongodb-query-exporter#45]
#### Describe the bug
We have run Mongo-query-EXPORTER after configuring as per the instructions,However, the following error occurs during query execution as shown in the following picture, would you mind to help us?
![image](https://user-images.githubusercontent.com/31676287/159877897-19222888-f719-4649-a84a-365f26802453.png)

![image](https://user-images.githubusercontent.com/31676287/159878021-a383dbc7-3d83-47ce-812b-51758704b23a.png)

#### Environment
 - mongodb-query-exporter version: [v1.0.0]
 - MongoDB version: [v3.6.1]

**Comment by gongmingsong** [comment]
Yes, I have tried to connect successfully

**Comment by raffis** [comment]
I reckon this pr #46 fixes it. Please change the query timeout to something more realistic :) .

**Comment by gongmingsong** [comment]
Thank you very much，the problem has been resolved
