### ISSUE TITLE
Suggestion: Have readPreference set to "secondaryPreferred" by default

### ISSUE THREAD

**Issue by johnnyshields** [raffis/mongodb-query-exporter#48]
I recommend that the query exporter be set to readPreference "secondaryPreferred" by default, so that it generally reads from secondaries rather than the primary.

The advantage of this is that it avoids load on your primary DB. In particular, aggregation pipeline queries often seem to lock the DB collection and make other queries (i.e. from your application) artificially slow.

The main disadvantage of this is that your exported metrics may be subject to replication lag (usually less than 1 sec) vs. the state of the primary. Since the query exporter is typically used for passive stats exporting, this is generally acceptable in the vast majority of cases.

**Comment by raffis** [comment]
I am not sure whether its a good idea to change the default behavior. What stops you from just changing the URI?
That said this is definitely worth documenting in the readme.

**Comment by reese-allison** [comment]
I have been experiencing an issue with this code respecting and read preference I try to set.

I have my URI declared in my ConfigMap like so:
`MDBEXPORTER_MONGODB_URI: mongodb+srv://username:password@cluster.mongodb.net?retryReads=true&authSource=admin&readPreference=secondary`

But when I check my profiler in Mongo, the same queries I setup in my ConfigMap are showing up with a different read preference.

<img width="178" alt="Screenshot 2023-06-16 at 5 57 30 PM" src="https://github.com/raffis/mongodb-query-exporter/assets/42069854/fcc780d2-dc79-4cee-bf54-97177adb67f0">

**Comment by johnnyshields** [comment]
This should be reopened. Adding to readme would be ok.
