### ISSUE TITLE
[Question about usage]

### ISSUE THREAD

**Issue by XaKSleed** [raffis/mongodb-query-exporter#57]
Hello, I have a problem, I have this database.
![image](https://user-images.githubusercontent.com/58429579/170112319-8d4bde83-5298-4fa5-9925-f11450f7b118.png)
And I am using this config
![image](https://user-images.githubusercontent.com/58429579/170115820-4da8181c-354f-4ea3-8053-feeb31657f21.png)

 when it works the following error occurs.
![image](https://user-images.githubusercontent.com/58429579/170115498-23b57425-23db-4311-8b5e-6694cc7a9a7d.png)

Could you please tell me what the problem is and how to write a correct query to the database for the correct work of the tool.
Or can you attach an example of a simple data find query?
Thank you in advance!

**Comment by raffis** [comment]
Probably your last character `]`, it is not indented. Please post configs in the future as text, it is not possible
for others to debug it with a screenshot, thanks.
