### ISSUE TITLE
Include binary file to the binary collection

### ISSUE THREAD

**Issue by Farfeght** [raffis/mongodb-query-exporter#58]
#### Describe the change
I expected to find file called "mongodb_query_exporter" from the package [prometheus-mongodb-query-exporter-2.1.0.tgz](https://github.com/raffis/mongodb-query-exporter/releases/download/prometheus-mongodb-query-exporter-2.1.0/prometheus-mongodb-query-exporter-2.1.0.tgz) but it isn't there. Could you add it?

#### Current situation
Command ls produces the following outcome `Chart.yaml  README.md  templates  values.yaml` .

#### Should
I guess command ls should produce something like `Chart.yaml  README.md  templates mongodb_query_exporter  values.yaml`

#### Additional context
I'm not experienced with prometheus, mongoDB or Go, so if there are things that I have overlooked I'm sorry.

**Comment by raffis** [comment]
You are referring to the helm chart. See the release for the exporter itself where you can find the binary: https://github.com/raffis/mongodb-query-exporter/releases/tag/v1.0.0

**Comment by Farfeght** [comment]
Ok, very good. Thank you.
I got the URL from README.md under "Installation". Got little sidetracked there.

In any case, this was helpful 👍

**Comment by raffis** [comment]
> Ok, very good. Thank you. I got the URL from README.md under "Installation". Got little sidetracked there.

Fair enough, I'll change that part.
