### ISSUE TITLE
Question about debugging

### ISSUE THREAD

**Issue by Farfeght** [raffis/mongodb-query-exporter#59]
I have managed to setup mongodb-query-exporter and i get the mongodb_query_exporter_query_total metric out of it.

Currently I'm unable to get my first aggregation to work, and I wonder is it connection error or configuration error. Could someone give any hints? Any idea what has happened to my kookoo aggregation?

My config is as follows:

```
version: 3.0
bind: 0.0.0.0:9412
log:
  encoding: json
  level: info
  development: false
  disableCaller: false
global:
  queryTimeout: 10
  maxConnection: 3
  defaultCache: 0
servers:
- name: main
  uri: [connection string from Azure portal that I know , works]
- metrics:
  - name: kookoo
    help: 'How many solutions presented in the cosmosDB'
    value: total
  database: mwise
  collection: solutions
  servers: [main]
  mode: push
  pipeline: |
    [
      {"$count":"total"}
    ]
```

And logging prints like this:

> 16:38:27 linux systemd[1]: Stopping MongoDB Query Exporter...
16:38:27 linux systemd[1]: Stopped MongoDB Query Exporter.
16:38:27 linux systemd[1]: Started MongoDB Query Exporter.
16:38:27 linux mongodb-query-exporter[20738]: {"level":"info","ts":1657719507.8708718,"caller":"v3/config.go:103","msg":"will listen on 0.0.0.0:9412"}
16:38:27 linux mongodb-query-exporter[20738]: {"level":"info","ts":1657719507.870922,"caller":"v3/config.go:141","msg":"use mongodb hosts []string{\"cosmos-mongo.mongo.cosmos.azure.com:10255\"}"}
16:38:27 linux mongodb-query-exporter[20738]: {"level":"info","ts":1657719507.871182,"caller":"collector/collector.go:341","msg":"start changestream on mwise.solutions, waiting for changes"}
16:38:28 linux mongodb-query-exporter[20738]: {"level":"error","ts":1657719508.9258626,"caller":"collector/collector.go:329","msg":"failed to start changestream listener (BadValue) fullDocument option must be \"updateLookup\".; failed to watch for updates, fallback to pull"}
16:38:37 linux mongodb-query-exporter[20738]: {"level":"error","ts":1657719517.7763827,"caller":"collector/collector.go:256","msg":"failed to generate metric: context deadline exceeded"}
16:38:52 linux mongodb-query-exporter[20738]: {"level":"error","ts":1657719532.7756834,"caller":"collector/collector.go:256","msg":"failed to generate metric: context deadline exceeded"}
16:39:07 linux mongodb-query-exporter[20738]: {"level":"error","ts":1657719547.7756813,"caller":"collector/collector.go:256","msg":"failed to generate metric: context deadline exceeded"}
16:39:22 linux mongodb-query-exporter[20738]: {"level":"error","ts":1657719562.7757967,"caller":"collector/collector.go:256","msg":"failed to generate metric: context deadline exceeded"}
16:39:37 linux mongodb-query-exporter[20738]: {"level":"error","ts":1657719577.7758172,"caller":"collector/collector.go:256","msg":"failed to generate metric: context deadline exceeded"}
16:39:52 linux mongodb-query-exporter[20738]: {"level":"error","ts":1657719592.7760677,"caller":"collector/collector.go:256","msg":"failed to generate metric: context deadline exceeded"}
16:40:07 linux mongodb-query-exporter[20738]: {"level":"error","ts":1657719607.777052,"caller":"collector/collector.go:256","msg":"failed to generate metric: context deadline exceeded"}
16:40:22 linux mongodb-query-exporter[20738]: {"level":"error","ts":1657719622.7757149,"caller":"collector/collector.go:256","msg":"failed to generate metric: context deadline exceeded"}
16:40:37 linux mongodb-query-exporter[20738]: {"level":"error","ts":1657719637.7755935,"caller":"collector/collector.go:256","msg":"failed to generate metric: timed out while checking out a connection from connection pool: context deadline exceeded; maxPoolSize: 100, connections in use by cursors: 0, connections in use by transactions: 0, connections in use by other operations: 0"}
16:40:52 linux mongodb-query-exporter[20738]: {"level":"error","ts":1657719652.775446,"caller":"collector/collector.go:256","msg":"failed to generate metric: timed out while checking out a connection from connection pool: context deadline exceeded; maxPoolSize: 100, connections in use by cursors: 0, connections in use by transactions: 0, connections in use by other operations: 0"}
16:41:07 linux mongodb-query-exporter[20738]: {"level":"error","ts":1657719667.775576,"caller":"collector/collector.go:256","msg":"failed to generate metric: timed out while checking out a connection from connection pool: context deadline exceeded; maxPoolSize: 100, connections in use by cursors: 0, connections in use by transactions: 0, connections in use by other operations: 0"}
16:41:22 linux mongodb-query-exporter[20738]: {"level":"error","ts":1657719682.7756364,"caller":"collector/collector.go:256","msg":"failed to generate metric: timed out while checking out a connection from connection pool: context deadline exceeded; maxPoolSize: 100, connections in use by cursors: 0, connections in use by transactions: 0, connections in use by other operations: 0"}
16:41:37 linux mongodb-query-exporter[20738]: {"level":"error","ts":1657719697.775633,"caller":"collector/collector.go:256","msg":"failed to generate metric: timed out while checking out a connection from connection pool: context deadline exceeded; maxPoolSize: 100, connections in use by cursors: 0, connections in use by transactions: 0, connections in use by other operations: 0"}
16:41:52 linux mongodb-query-exporter[20738]: {"level":"error","ts":1657719712.7755651,"caller":"collector/collector.go:256","msg":"failed to generate metric: timed out while checking out a connection from connection pool: context deadline exceeded; maxPoolSize: 100, connections in use by cursors: 0, connections in use by transactions: 0, connections in use by other operations: 0"}
16:42:07 linux mongodb-query-exporter[20738]: {"level":"error","ts":1657719727.7757118,"caller":"collector/collector.go:256","msg":"failed to generate metric: timed out while checking out a connection from connection pool: context deadline exceeded; maxPoolSize: 100, connections in use by cursors: 0, connections in use by transactions: 0, connections in use by other operations: 0"}
...

BR

**Comment by raffis** [comment]
There is a really short timeout of 10ns configured.
Try replacing `queryTimeout: 10` with `queryTimeout: 10s`.

**Comment by Farfeght** [comment]
Hah =D . Somehow I did not realize that I need to add that unit there. I humbly thank thee!
