### ISSUE TITLE
MongoDB uri password as env

### ISSUE THREAD

**Issue by ajila-fmeyer** [raffis/mongodb-query-exporter#6]
Hi @raffis 

I'm trying to authenticate against my MongoDB with the password set environment variables in uri.
Example:  
> uri: mongodb://test:$TEST@localhost

Unfortunately this does not seem to work and the following message appears in the log.
> auth error: sasl conversation error: unable to authenticate using mechanism \"SCRAM-SHA-256\": (AuthenticationFailed) Authentication failed., awaiting the next pull.

Do you know the error respectively does your go application not support the MongoDB User Password as ENV in uri string?

**Comment by raffis** [comment]
> Hi @raffis
> 
> I'm trying to authenticate against my MongoDB with the password set environment variables in uri.
> Example:

What you can do is to inject the whole connection URI from an env: `MDBEXPORTER_MONGODB_URI`. Does this solve your issue?

**Comment by ajila-fmeyer** [comment]
You mean 

> data:
  config.yaml: |
    bind: 0.0.0.0:9412
    logLevel: info
    mongodb:
      uri: "$MDBEXPORTER_MONGODB_URI"
      connectionTimeout: 3
      maxConnection: 3
      defaultInterval: 5

or only set as ENV in container without any reference to `config.yaml`?

**Comment by raffis** [comment]
> or only set as ENV in container without any reference to `config.yaml`?

You don't need to reference it, it automatically gets picked up if that env exists.

**Comment by ajila-fmeyer** [comment]
Thanks for your fast support. It works as expected with setting `MDBEXPORTER_MONGODB_URI` as env 👍
