### ISSUE TITLE
Question about connection MongoAtlas

### ISSUE THREAD

**Issue by cerealekiller-mike** [raffis/mongodb-query-exporter#61]
Hi,

I'm trying to integrate this exporter to collect metrics from MongoAtlas database.

When I try to collect it I got an issue. 

{"level":"error","ts":1669911025.5999675,"caller":"collector/collector.go:256","msg":"failed to generate metric: server selection error: context deadline exceeded, current topology: { Type: ReplicaSetNoPrimary, Servers: [{ Addr: <adr1>:1234, Type: Unknown, Last error: connection() error occured during connection handshake: dial tcp <ip>:1235: i/o timeout }, { Addr: <adr1>:1236, Type: Unknown, Last error: connection() error occured during connection handshake: dial tcp <adr1>:1237: i/o timeout }, { Addr: <adr1>:1038, Type: Unknown, Last error: connection() error occured during connection handshake: dial tcp <ip>:1238: i/o timeout }, ] }"}

The resolution seems be good but the issue seems to be linked about the ssl protocol but on other containers on the same machines where connection to same mongodb database is done and no issue. 

Could you help me ?

**Comment by raffis** [comment]
Can you please post the exporter config?

**Comment by cerealekiller-mike** [comment]
version: 3.0
bind: 0.0.0.0:9412
metricsPath: /metrics
log:
  encoding: json
  level: debug
  development: false
  disableCaller: false
global:
  queryTimeout: "10s"
  maxConnection: 3
  defaultCache: 0
servers:
- name: main
  uri: mongodb://localhost:27017
aggregations:
- database: sales_salesbackoffice
  collection: till
  metrics:
  - name: salesbackoffice_opened_tills_total
    type: gauge
    help: 'The total number of opened tills'
    value: total
    labels: [storeId]
    constLabels: []
  mode: pull
  cache: "5m"
  pipeline: |
    [
      {
        "$group": {
          "_id": "$storeId",
          "total": {
            "$sum": {
              "$cond": [ { "$eq": ["$state", "OPENED"] }, 1, 0 ]
            }
          }
        }
      }, {
        "$set": {
          "storeId": "$_id"
        }
      }
    ]

**Comment by cerealekiller-mike** [comment]
#
# MONGODB EXPORTER
#
MY_USERNAME=myUser
MY_PASSWORD=myPwd
MDBEXPORTER_MONGODB_URI=mongodb+srv://${MY_USERNAME}:${MY_PASSWORD}@host_mongodb/test
MDBEXPORTER_CONFIG=./config/mongodb_exporter.yml
MDBEXPORTER_LOG_LEVEL=debug

**Comment by raffis** [comment]
This does not look like a problem with the exporter, either you have something wrong on the network or configured a wrong uri. Can you access `mongo mongodb+srv://${MY_USERNAME}:${MY_PASSWORD}@host_mongodb/test` from that machine?

**Comment by cerealekiller-mike** [comment]
Hi due to a firewall modification between my test with an another exporter the mongo command was blocked
I'haven't retested before so that's why it doesn't works/. So simple tests find simple reasons.

Thanks
